Add crystal shards support
Lukc/build.zsh pull request #1
Opened 2018-08-06 13:36 UTC by Stygmates

2018-08-07 12:56 UTC, Lukc requested changes

2018-08-07 12:56 UTC, Lukc commented on build/shards.zsh
> +	write "\t${Q}shards build"
Is not related to the target. You could have a `make foo` that doesn’t build foo.

2018-08-07 12:56 UTC, Lukc commented on build/shards.zsh
> +	echo "${target}"
shards will rely on things from lib/ and its shard.yml. lib/ can be ignored if you run `shards update` somewhere, but shard.yml will be needed, and only once.

2019-11-05 00:22 UTC, Lukc commented
Hi @Stygmates! Are you still working on this? Can I close the PR, or are you still interested in having native shards support?

2019-11-06 00:14 UTC, Stygmates commented
I'm not working on this anymore, closing this PR.

2019-11-06 00:14 UTC, closed without merging